/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Auth Status */
    get: operations["auth_status_api_v1_auth_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Setup */
    post: operations["setup_api_v1_auth_setup_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Settings */
    get: operations["settings_api_v1_settings_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/settings/agent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Agent */
    put: operations["update_agent_api_v1_settings_agent_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/settings/openai": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Openai Settings */
    put: operations["openai_settings_api_v1_settings_openai_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/openai/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Models */
    get: operations["models_api_v1_openai_models_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/openai/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Openai Test */
    post: operations["openai_test_api_v1_openai_test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/settings/microsoft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Microsoft Settings */
    put: operations["microsoft_settings_api_v1_settings_microsoft_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/microsoft/auth": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Microsoft Auth */
    post: operations["microsoft_auth_api_v1_microsoft_auth_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/microsoft/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Microsoft Callback */
    get: operations["microsoft_callback_api_v1_microsoft_callback_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/microsoft/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Microsoft Test */
    post: operations["microsoft_test_api_v1_microsoft_test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/microsoft/discover/{kind}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Discover */
    get: operations["discover_api_v1_microsoft_discover__kind__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sources */
    get: operations["sources_api_v1_sources_get"];
    put?: never;
    /** Create Source */
    post: operations["create_source_api_v1_sources_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/microsoft/chats/page": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chat Page */
    get: operations["chat_page_api_v1_microsoft_chats_page_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sources/{source_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Source */
    patch: operations["update_source_api_v1_sources__source_id__patch"];
    trace?: never;
  };
  "/api/v1/sources/{source_id}/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sync */
    post: operations["sync_api_v1_sources__source_id__sync_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Items */
    get: operations["items_api_v1_items_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/items/{item_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Item */
    get: operations["get_item_api_v1_items__item_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Item Status */
    patch: operations["item_status_api_v1_items__item_id__patch"];
    trace?: never;
  };
  "/api/v1/items/{item_id}/file": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get File */
    get: operations["get_file_api_v1_items__item_id__file_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/items/{item_id}/citation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Citation */
    get: operations["citation_api_v1_items__item_id__citation_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/items/{item_id}/analyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Analyze Item */
    post: operations["analyze_item_api_v1_items__item_id__analyze_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search */
    get: operations["search_api_v1_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload */
    post: operations["upload_api_v1_documents_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/knowledge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Note */
    post: operations["create_note_api_v1_knowledge_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/knowledge/{item_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Note */
    put: operations["update_note_api_v1_knowledge__item_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/knowledge/{item_id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Versions */
    get: operations["versions_api_v1_knowledge__item_id__versions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/knowledge/{item_id}/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore Note */
    post: operations["restore_note_api_v1_knowledge__item_id__restore_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/knowledge/reindex/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reindex */
    post: operations["reindex_api_v1_knowledge_reindex_all_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/conversations/{conversation_id}/email-reply-draft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Email Reply Draft */
    post: operations["email_reply_draft_api_v1_conversations__conversation_id__email_reply_draft_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Conversations */
    get: operations["conversations_api_v1_conversations_get"];
    put?: never;
    /** Create Conversation */
    post: operations["create_conversation_api_v1_conversations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/conversations/{conversation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Conversation Detail */
    get: operations["conversation_detail_api_v1_conversations__conversation_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Link Conversation */
    patch: operations["link_conversation_api_v1_conversations__conversation_id__patch"];
    trace?: never;
  };
  "/api/v1/conversations/{conversation_id}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chat Message */
    post: operations["chat_message_api_v1_conversations__conversation_id__messages_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/proposals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Proposals */
    get: operations["proposals_api_v1_proposals_get"];
    put?: never;
    /** Create Proposal */
    post: operations["create_proposal_api_v1_proposals_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/proposals/{proposal_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Edit Proposal */
    put: operations["edit_proposal_api_v1_proposals__proposal_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/proposals/{proposal_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve Proposal */
    post: operations["approve_proposal_api_v1_proposals__proposal_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/proposals/{proposal_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject Proposal */
    post: operations["reject_proposal_api_v1_proposals__proposal_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Activity */
    get: operations["activity_api_v1_activity_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations["events_api_v1_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/github/connections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Connections */
    get: operations["connections_api_v1_github_connections_get"];
    put?: never;
    /** Create Connection */
    post: operations["create_connection_api_v1_github_connections_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/github/connections/{identity}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Connection */
    delete: operations["delete_connection_api_v1_github_connections__identity__delete"];
    options?: never;
    head?: never;
    /** Update Connection */
    patch: operations["update_connection_api_v1_github_connections__identity__patch"];
    trace?: never;
  };
  "/api/v1/github/connections/{identity}/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test Connection */
    post: operations["test_connection_api_v1_github_connections__identity__test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/github/repositories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Repositories */
    get: operations["repositories_api_v1_github_repositories_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/github/repositories/{identity}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Repository */
    patch: operations["update_repository_api_v1_github_repositories__identity__patch"];
    trace?: never;
  };
  "/api/v1/github/issues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Issues */
    get: operations["issues_api_v1_github_issues_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/github/labels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Issue Labels */
    get: operations["issue_labels_api_v1_github_labels_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/github/issues/{identity}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Issue Detail */
    get: operations["issue_detail_api_v1_github_issues__identity__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Issue */
    patch: operations["update_issue_api_v1_github_issues__identity__patch"];
    trace?: never;
  };
  "/api/v1/github/issues/{identity}/conversation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Link Chat */
    post: operations["link_chat_api_v1_github_issues__identity__conversation_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/github/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sync */
    post: operations["sync_api_v1_github_sync_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tasks */
    get: operations["tasks_api_v1_tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/calendar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Calendar */
    get: operations["calendar_api_v1_calendar_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActionPayload */
    ActionPayload: {
      /** Source Id */
      source_id?: string | null;
      /** Item Id */
      item_id?: string | null;
      /** Title */
      title?: string | null;
      /** Subject */
      subject?: string | null;
      /** Body */
      body?: string | null;
      /** Content */
      content?: string | null;
      /** Recipient */
      recipient?: string | null;
      /** Due */
      due?: string | null;
      /** Start */
      start?: string | null;
      /** End */
      end?: string | null;
      /** Attendees */
      attendees?: string[];
      /** Expected Version */
      expected_version?: number | null;
    } & {
      [key: string]: unknown;
    };
    /** ActionResult */
    ActionResult: {
      /** Error */
      error?: string | null;
      /** Message */
      message?: string | null;
    } & {
      [key: string]: unknown;
    };
    /** ActivityView */
    ActivityView: {
      /** Jobs */
      jobs: components["schemas"]["JobView"][];
      /** Audit */
      audit: components["schemas"]["AuditView"][];
      usage: components["schemas"]["UsageSummary"];
      worker: components["schemas"]["WorkerStatus"];
    };
    /** AgentProfile */
    AgentProfile: {
      /** Model */
      model: string;
      /** Embedding Model */
      embedding_model: string;
      /** Instructions */
      instructions: string;
      /** Style */
      style: string;
      /** Daily Limit */
      daily_limit: number;
      /** Paused */
      paused: boolean;
      /** Allowed Actions */
      allowed_actions: string[];
    };
    /** AgentSettings */
    AgentSettings: {
      /**
       * Model
       * @default
       */
      model: string;
      /**
       * Embedding Model
       * @default text-embedding-3-small
       */
      embedding_model: string;
      /** Instructions */
      instructions: string;
      /** Style */
      style: string;
      /** Daily Limit */
      daily_limit: number;
      /** Paused */
      paused: boolean;
      /** Allowed Actions */
      allowed_actions: string[];
    };
    /** AuditView */
    AuditView: {
      /** Id */
      id: number;
      /** Action */
      action: string;
      /** Detail */
      detail: {
        [key: string]: unknown;
      };
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** AuthStart */
    AuthStart: {
      /** Kind */
      kind?: string | null;
      /**
       * Write
       * @default false
       */
      write: boolean;
    };
    /** AuthStatus */
    AuthStatus: {
      /** Initialized */
      initialized: boolean;
      /** Authenticated */
      authenticated: boolean;
      /** Csrf */
      csrf?: string | null;
      /** Demo */
      demo: boolean;
    };
    /** AuthUrl */
    AuthUrl: {
      /** Url */
      url: string;
    };
    /** Body_upload_api_v1_documents_post */
    Body_upload_api_v1_documents_post: {
      /** File */
      file: string;
    };
    /**
     * CalendarView
     * @description Calendar metadata includes start/end with source timezone.
     */
    CalendarView: {
      /** Id */
      id: string;
      /** Source Id */
      source_id: string;
      /** External Id */
      external_id: string;
      /** Kind */
      kind: string;
      /** Title */
      title: string;
      /** Body */
      body: string;
      /** Sender */
      sender: string;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** Thread Key */
      thread_key: string;
      /** Web Url */
      web_url: string;
      meta: components["schemas"]["ItemMetadata"];
      /** Content Hash */
      content_hash: string;
      /** Available */
      available: boolean;
      /** Status */
      status: string;
      /** Summary */
      summary: string;
      /** Version */
      version: number;
      /** Processing */
      processing: string;
      /** Processing Error */
      processing_error?: string | null;
      /** Source Name */
      source_name: string;
      /** Source Kind */
      source_kind: string;
      /** Ai Enabled */
      ai_enabled: boolean;
    };
    /** ChatChoice */
    ChatChoice: {
      /** Id */
      id: string;
      /** Topic */
      topic: string;
      /** Chattype */
      chatType?: string | null;
      /** Participants */
      participants: string[];
    };
    /** ChatChoicePage */
    ChatChoicePage: {
      /** Items */
      items: components["schemas"]["ChatChoice"][];
      /** Continuation */
      continuation?: string | null;
    };
    /** ChatInput */
    ChatInput: {
      /** Content */
      content: string;
    };
    /** Citation */
    Citation: {
      /** Item Id */
      item_id: string;
      /**
       * Title
       * @default
       */
      title: string;
      /**
       * Locator
       * @default Original
       */
      locator: string;
      /**
       * Version
       * @default 1
       */
      version: number;
      /** Available */
      available?: boolean | null;
      /** Chunk Id */
      chunk_id?: string | null;
    };
    /** CitationView */
    CitationView: {
      /** Text */
      text: string;
      /** Locator */
      locator: string;
      /** Version */
      version: number;
    };
    /** CommentView */
    CommentView: {
      /** Id */
      id: string;
      /** Author */
      author: string;
      /** Body */
      body: string;
      /** Web Url */
      web_url: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ConnectionInput */
    ConnectionInput: {
      /** Owner */
      owner: string;
      /** Name */
      name: string;
      /** Token */
      token: string;
    };
    /** ConnectionTest */
    ConnectionTest: {
      /** Ok */
      ok: boolean;
      /** Repositories */
      repositories: number;
      /** Message */
      message: string;
    };
    /** ConnectionUpdate */
    ConnectionUpdate: {
      /** Token */
      token?: string | null;
      /** Enabled */
      enabled?: boolean | null;
    };
    /** ConnectionView */
    ConnectionView: {
      /** Id */
      id: string;
      /** Owner */
      owner: string;
      /** Name */
      name: string;
      /** Enabled */
      enabled: boolean;
      /** Demo */
      demo: boolean;
      /** Status */
      status: string;
      /** Error */
      error: string | null;
      /** Last Discovery */
      last_discovery: string | null;
      /** Retry At */
      retry_at: string | null;
    };
    /** ConversationDetail */
    ConversationDetail: {
      conversation: components["schemas"]["ConversationView"];
      /** Items */
      items: (
        | components["schemas"]["ItemView"]
        | components["schemas"]["UnavailableItem"]
      )[];
      /** Messages */
      messages: components["schemas"]["MessageView"][];
      /** Proposals */
      proposals: components["schemas"]["ProposalView"][];
    };
    /** ConversationInput */
    ConversationInput: {
      /**
       * Title
       * @default Neuer Arbeitschat
       */
      title: string;
      /** Item Ids */
      item_ids?: string[];
    };
    /** ConversationView */
    ConversationView: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Item Ids */
      item_ids: string[];
      /** Thread Key */
      thread_key?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** DiscoveryEntry */
    DiscoveryEntry: {
      /** Id */
      id: string;
      /** Name */
      name?: string | null;
      /** Displayname */
      displayName?: string | null;
      /** Topic */
      topic?: string | null;
    } & {
      [key: string]: unknown;
    };
    /** EmailReplyDraftInput */
    EmailReplyDraftInput: {
      /** Message Id */
      message_id: string;
      /** Item Id */
      item_id: string;
      /** Body */
      body: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
    };
    /** IssueDetail */
    IssueDetail: {
      /** Id */
      id: string;
      /** Repository Id */
      repository_id: string;
      /** Repository */
      repository: string;
      /** Owner */
      owner: string;
      /** Item Id */
      item_id: string;
      /** Number */
      number: number;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Author */
      author: string;
      /** Web Url */
      web_url: string;
      /** State */
      state: string;
      /** Local Status */
      local_status: string;
      /** Labels */
      labels: string[];
      /** Assignees */
      assignees: string[];
      /** Milestone */
      milestone: string | null;
      /** Pull Requests */
      pull_requests: components["schemas"]["PullRequestView"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Closed At */
      closed_at: string | null;
      /** Ai Enabled */
      ai_enabled: boolean;
      /** Demo */
      demo: boolean;
      /** Codex Prompt */
      codex_prompt: string;
      /** Comments */
      comments: components["schemas"]["CommentView"][];
      /** Conversations */
      conversations: components["schemas"]["ConversationView"][];
    };
    /** IssuePage */
    IssuePage: {
      /** Items */
      items: components["schemas"]["IssueView"][];
      /** Total */
      total: number;
    };
    /** IssueView */
    IssueView: {
      /** Id */
      id: string;
      /** Repository Id */
      repository_id: string;
      /** Repository */
      repository: string;
      /** Owner */
      owner: string;
      /** Item Id */
      item_id: string;
      /** Number */
      number: number;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Author */
      author: string;
      /** Web Url */
      web_url: string;
      /** State */
      state: string;
      /** Local Status */
      local_status: string;
      /** Labels */
      labels: string[];
      /** Assignees */
      assignees: string[];
      /** Milestone */
      milestone: string | null;
      /** Pull Requests */
      pull_requests: components["schemas"]["PullRequestView"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Closed At */
      closed_at: string | null;
      /** Ai Enabled */
      ai_enabled: boolean;
      /** Demo */
      demo: boolean;
      /** Codex Prompt */
      codex_prompt: string;
    };
    /** ItemMetadata */
    ItemMetadata: {
      /**
       * Demo
       * @default false
       */
      demo: boolean;
      start?: components["schemas"]["SourceTime"] | null;
      end?: components["schemas"]["SourceTime"] | null;
      /** Due */
      due?: components["schemas"]["SourceTime"] | string | null;
      /** Citations */
      citations?: components["schemas"]["Citation"][];
    } & {
      [key: string]: unknown;
    };
    /** ItemStatus */
    ItemStatus: {
      /** Status */
      status: string;
    };
    /** ItemView */
    ItemView: {
      /** Id */
      id: string;
      /** Source Id */
      source_id: string;
      /** External Id */
      external_id: string;
      /** Kind */
      kind: string;
      /** Title */
      title: string;
      /** Body */
      body: string;
      /** Sender */
      sender: string;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** Thread Key */
      thread_key: string;
      /** Web Url */
      web_url: string;
      meta: components["schemas"]["ItemMetadata"];
      /** Content Hash */
      content_hash: string;
      /** Available */
      available: boolean;
      /** Status */
      status: string;
      /** Summary */
      summary: string;
      /** Version */
      version: number;
      /** Processing */
      processing: string;
      /** Processing Error */
      processing_error?: string | null;
      /** Source Name */
      source_name: string;
      /** Source Kind */
      source_kind: string;
      /** Ai Enabled */
      ai_enabled: boolean;
    };
    /** JobView */
    JobView: {
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Dedupe Key */
      dedupe_key?: string | null;
      /** Status */
      status: string;
      /** Attempts */
      attempts: number;
      /**
       * Run After
       * Format: date-time
       */
      run_after: string;
      /** Started At */
      started_at?: string | null;
      /** Error */
      error?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** KeySettings */
    KeySettings: {
      /** Api Key */
      api_key: string;
    };
    /** KnowledgeVersionView */
    KnowledgeVersionView: {
      /** Id */
      id: string;
      /** Item Id */
      item_id: string;
      /** Version */
      version: number;
      /** Title */
      title: string;
      /** Content */
      content: string;
      /** Citations */
      citations: components["schemas"]["Citation"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** LocalStatusInput */
    LocalStatusInput: {
      /** Status */
      status: string;
    };
    /** Login */
    Login: {
      /** Password */
      password: string;
      /**
       * Demo
       * @default false
       */
      demo: boolean;
    };
    /** MessageView */
    MessageView: {
      /** Id */
      id: string;
      /** Conversation Id */
      conversation_id: string;
      /** Role */
      role: string;
      /** Content */
      content: string;
      /** Citations */
      citations: components["schemas"]["Citation"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** MicrosoftAccount */
    MicrosoftAccount: {
      /** Oid */
      oid?: string | null;
      /** Name */
      name?: string | null;
      /** Username */
      username?: string | null;
    };
    /** MicrosoftConfiguration */
    MicrosoftConfiguration: {
      /** Tenant Id */
      tenant_id?: string | null;
      /** Client Id */
      client_id?: string | null;
    };
    /** MicrosoftProfile */
    MicrosoftProfile: {
      /** Displayname */
      displayName?: string | null;
      /** Userprincipalname */
      userPrincipalName?: string | null;
    };
    /** MicrosoftSettings */
    MicrosoftSettings: {
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string;
      /**
       * Client Id
       * Format: uuid
       */
      client_id: string;
      /**
       * Client Secret
       * @default
       */
      client_secret: string;
    };
    /** ModelTest */
    ModelTest: {
      /** Ok */
      ok: boolean;
      /** Answer */
      answer: string;
      /** Embedding Dimension */
      embedding_dimension: number;
    };
    /** NoteInput */
    NoteInput: {
      /** Title */
      title: string;
      /** Content */
      content: string;
      /** Expected Version */
      expected_version?: number | null;
    };
    /** Ok */
    Ok: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /** ProposalInput */
    ProposalInput: {
      /** Kind */
      kind: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Item Id */
      item_id?: string | null;
      /** Conversation Id */
      conversation_id?: string | null;
      /** Version */
      version?: number | null;
    };
    /** ProposalView */
    ProposalView: {
      /** Id */
      id: string;
      /** Conversation Id */
      conversation_id?: string | null;
      /** Item Id */
      item_id?: string | null;
      /** Kind */
      kind: string;
      payload: components["schemas"]["ActionPayload"];
      /** Citations */
      citations: components["schemas"]["Citation"][];
      /** Version */
      version: number;
      /** Status */
      status: string;
      /** Approved Hash */
      approved_hash?: string | null;
      result: components["schemas"]["ActionResult"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** PullRequestView */
    PullRequestView: {
      /** Number */
      number: number;
      /** Title */
      title: string;
      /** Url */
      url: string;
      /** State */
      state: string;
    };
    /** RepositoryUpdate */
    RepositoryUpdate: {
      /** Enabled */
      enabled?: boolean | null;
      /** Ai Enabled */
      ai_enabled?: boolean | null;
    };
    /** RepositoryView */
    RepositoryView: {
      /** Id */
      id: string;
      /** Connection Id */
      connection_id: string;
      /** Source Id */
      source_id: string;
      /** Owner */
      owner: string;
      /** Name */
      name: string;
      /** Full Name */
      full_name: string;
      /** Web Url */
      web_url: string;
      /** Default Branch */
      default_branch: string;
      /** Archived */
      archived: boolean;
      /** Enabled */
      enabled: boolean;
      /** Ai Enabled */
      ai_enabled: boolean;
      /** Status */
      status: string;
      /** Error */
      error: string | null;
      /** Demo */
      demo: boolean;
      /** Last Sync */
      last_sync: string | null;
    };
    /** RestoreVersion */
    RestoreVersion: {
      /** Version */
      version: number;
      /** Expected Version */
      expected_version: number;
    };
    /** SearchHit */
    SearchHit: {
      /** Item Id */
      item_id: string;
      /** Chunk Id */
      chunk_id: string;
      /** Title */
      title: string;
      /** Locator */
      locator: string;
      /** Text */
      text: string;
      /** Version */
      version: number;
      /** Score */
      score?: number | null;
    };
    /** SessionCreated */
    SessionCreated: {
      /** Csrf */
      csrf: string;
    };
    /** SettingsView */
    SettingsView: {
      agent: components["schemas"]["AgentProfile"];
      /** Openai Configured */
      openai_configured: boolean;
      microsoft: components["schemas"]["MicrosoftConfiguration"];
      /** Microsoft Configured */
      microsoft_configured: boolean;
      account: components["schemas"]["MicrosoftAccount"];
      /** Redirect Uri */
      redirect_uri: string;
      worker: components["schemas"]["WorkerStatus"];
    };
    /** SourceConfiguration */
    SourceConfiguration: {
      /**
       * Demo
       * @default false
       */
      demo: boolean;
      /**
       * Days
       * @default 90
       */
      days: number;
      /** Folder Id */
      folder_id?: string | null;
      /** Chat Id */
      chat_id?: string | null;
      /** Team Id */
      team_id?: string | null;
      /** Channel Id */
      channel_id?: string | null;
      /** Calendar Id */
      calendar_id?: string | null;
      /** List Id */
      list_id?: string | null;
      /** Drive Id */
      drive_id?: string | null;
      /** Repository Id */
      repository_id?: string | null;
      /** Connection Id */
      connection_id?: string | null;
    } & {
      [key: string]: unknown;
    };
    /** SourceInput */
    SourceInput: {
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      /** Config */
      config?: {
        [key: string]: unknown;
      };
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Ai Enabled
       * @default false
       */
      ai_enabled: boolean;
      /**
       * Writable
       * @default false
       */
      writable: boolean;
    };
    /** SourceTime */
    SourceTime: {
      /** Datetime */
      dateTime: string;
      /** Timezone */
      timeZone?: string | null;
    };
    /** SourceUpdate */
    SourceUpdate: {
      /** Enabled */
      enabled?: boolean | null;
      /** Ai Enabled */
      ai_enabled?: boolean | null;
      /** Writable */
      writable?: boolean | null;
      /** Days */
      days?: number | null;
    };
    /** SourceView */
    SourceView: {
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      config: components["schemas"]["SourceConfiguration"];
      /** Enabled */
      enabled: boolean;
      /** Ai Enabled */
      ai_enabled: boolean;
      /** Writable */
      writable: boolean;
      /** Status */
      status: string;
      /** Error */
      error?: string | null;
      /** Cursor */
      cursor: {
        [key: string]: unknown;
      };
      /** Last Sync */
      last_sync?: string | null;
      /**
       * Next Sync
       * Format: date-time
       */
      next_sync: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** SyncInput */
    SyncInput: {
      /** Connection Id */
      connection_id?: string | null;
      /** Repository Id */
      repository_id?: string | null;
    };
    /**
     * TaskView
     * @description Task metadata includes due date and source status.
     */
    TaskView: {
      /** Id */
      id: string;
      /** Source Id */
      source_id: string;
      /** External Id */
      external_id: string;
      /** Kind */
      kind: string;
      /** Title */
      title: string;
      /** Body */
      body: string;
      /** Sender */
      sender: string;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** Thread Key */
      thread_key: string;
      /** Web Url */
      web_url: string;
      meta: components["schemas"]["ItemMetadata"];
      /** Content Hash */
      content_hash: string;
      /** Available */
      available: boolean;
      /** Status */
      status: string;
      /** Summary */
      summary: string;
      /** Version */
      version: number;
      /** Processing */
      processing: string;
      /** Processing Error */
      processing_error?: string | null;
      /** Source Name */
      source_name: string;
      /** Source Kind */
      source_kind: string;
      /** Ai Enabled */
      ai_enabled: boolean;
    };
    /** UnavailableItem */
    UnavailableItem: {
      /** Id */
      id: string;
      /**
       * Available
       * @default false
       */
      available: boolean;
      /** Title */
      title: string;
    };
    /** UsageSummary */
    UsageSummary: {
      /** Calls */
      calls: number;
      /** Input Tokens */
      input_tokens: number;
      /** Output Tokens */
      output_tokens: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VersionInput */
    VersionInput: {
      /** Version */
      version: number;
    };
    /** WorkerStatus */
    WorkerStatus: {
      /** Heartbeat */
      heartbeat?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_status_api_v1_auth_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthStatus"];
        };
      };
    };
  };
  setup_api_v1_auth_setup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Login"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionCreated"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Login"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionCreated"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
    };
  };
  settings_api_v1_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsView"];
        };
      };
    };
  };
  update_agent_api_v1_settings_agent_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgentSettings"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  openai_settings_api_v1_settings_openai_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KeySettings"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  models_api_v1_openai_models_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  openai_test_api_v1_openai_test_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelTest"];
        };
      };
    };
  };
  microsoft_settings_api_v1_settings_microsoft_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MicrosoftSettings"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  microsoft_auth_api_v1_microsoft_auth_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthStart"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthUrl"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  microsoft_callback_api_v1_microsoft_callback_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  microsoft_test_api_v1_microsoft_test_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MicrosoftProfile"];
        };
      };
    };
  };
  discover_api_v1_microsoft_discover__kind__get: {
    parameters: {
      query?: {
        parent?: string | null;
        site_url?: string | null;
      };
      header?: never;
      path: {
        kind: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscoveryEntry"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sources_api_v1_sources_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceView"][];
        };
      };
    };
  };
  create_source_api_v1_sources_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chat_page_api_v1_microsoft_chats_page_get: {
    parameters: {
      query?: {
        continuation?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatChoicePage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_source_api_v1_sources__source_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sync_api_v1_sources__source_id__sync_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  items_api_v1_items_get: {
    parameters: {
      query?: {
        kind?: string | null;
        source_id?: string | null;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemView"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_item_api_v1_items__item_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  item_status_api_v1_items__item_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemStatus"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_file_api_v1_items__item_id__file_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  citation_api_v1_items__item_id__citation_get: {
    parameters: {
      query?: {
        locator?: string;
        version?: number | null;
      };
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CitationView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  analyze_item_api_v1_items__item_id__analyze_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_api_v1_search_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchHit"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_api_v1_documents_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_api_v1_documents_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_note_api_v1_knowledge_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NoteInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_note_api_v1_knowledge__item_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NoteInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  versions_api_v1_knowledge__item_id__versions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KnowledgeVersionView"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  restore_note_api_v1_knowledge__item_id__restore_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RestoreVersion"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reindex_api_v1_knowledge_reindex_all_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
    };
  };
  email_reply_draft_api_v1_conversations__conversation_id__email_reply_draft_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailReplyDraftInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  conversations_api_v1_conversations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationView"][];
        };
      };
    };
  };
  create_conversation_api_v1_conversations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConversationInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  conversation_detail_api_v1_conversations__conversation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  link_conversation_api_v1_conversations__conversation_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConversationInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chat_message_api_v1_conversations__conversation_id__messages_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  proposals_api_v1_proposals_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalView"][];
        };
      };
    };
  };
  create_proposal_api_v1_proposals_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProposalInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_proposal_api_v1_proposals__proposal_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        proposal_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProposalInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_proposal_api_v1_proposals__proposal_id__approve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        proposal_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reject_proposal_api_v1_proposals__proposal_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        proposal_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  activity_api_v1_activity_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivityView"];
        };
      };
    };
  };
  events_api_v1_events_get: {
    parameters: {
      query?: {
        after?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  connections_api_v1_github_connections_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionView"][];
        };
      };
    };
  };
  create_connection_api_v1_github_connections_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnectionInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_connection_api_v1_github_connections__identity__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        identity: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_connection_api_v1_github_connections__identity__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        identity: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnectionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  test_connection_api_v1_github_connections__identity__test_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        identity: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionTest"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  repositories_api_v1_github_repositories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryView"][];
        };
      };
    };
  };
  update_repository_api_v1_github_repositories__identity__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        identity: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RepositoryUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  issues_api_v1_github_issues_get: {
    parameters: {
      query?: {
        owner?: string | null;
        repository_id?: string | null;
        state?: string | null;
        label?: string | null;
        assignee?: string | null;
        local_status?: string | null;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssuePage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  issue_labels_api_v1_github_labels_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  issue_detail_api_v1_github_issues__identity__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        identity: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_issue_api_v1_github_issues__identity__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        identity: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LocalStatusInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  link_chat_api_v1_github_issues__identity__conversation_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        identity: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sync_api_v1_github_sync_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SyncInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  tasks_api_v1_tasks_get: {
    parameters: {
      query?: {
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskView"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  calendar_api_v1_calendar_get: {
    parameters: {
      query?: {
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CalendarView"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
